# Generated by Django 4.1.4 on 2023-07-25 10:25

import Backend.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Unique_Key', models.CharField(default=Backend.models.keygenerator, editable=False, max_length=50, unique=True)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('lat', models.CharField(max_length=150, null=True)),
                ('lon', models.CharField(max_length=150, null=True)),
                ('Active', models.BooleanField(default=False, null=True)),
                ('Description', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Index_pattern', models.CharField(max_length=100, null=True)),
                ('Data_view_id', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Location', models.CharField(max_length=150, null=True)),
                ('Description', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Contact_person', models.CharField(max_length=150, null=True)),
                ('Phone_Number', models.IntegerField(null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Status', models.CharField(choices=[('-1', 'Rejected'), ('1', 'Approved'), ('2', 'Pending')], default=2, max_length=150)),
                ('Website', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Index_template', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watcher',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Api_key_hash', models.CharField(default=Backend.models.keygenerator, editable=False, max_length=50, null=True)),
                ('Description', models.TextField(null=True)),
                ('Watcher_id', models.CharField(max_length=250, null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.device')),
            ],
        ),
        migrations.CreateModel(
            name='UseCases',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Description', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Dashboard_link', models.URLField(max_length=300, null=True)),
                ('Dashboard_id', models.CharField(max_length=50, null=True)),
                ('Division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.division')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('ID', models.SlugField(default=uuid.uuid1, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Role_name', models.CharField(max_length=150, null=True)),
                ('Is_Admin', models.BooleanField(default=False, null=True)),
                ('Is_Super_Admin', models.BooleanField(default=False, null=True)),
                ('Mode', models.CharField(choices=[('Viewer', 'Editor'), ('Editor', 'Editor'), ('Super Editor', 'Super Editor')], default='Viewer', max_length=25)),
                ('Division_list', models.CharField(max_length=100, null=True)),
                ('Usecase_list', models.CharField(max_length=200, null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.organization')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Job_Description', models.CharField(max_length=150, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.organization')),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.role')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Type', models.CharField(choices=[('Temperature', 'Temperature'), ('Humidity', 'Humidity'), ('Light', 'Light'), ('Pressure', 'Pressure'), ('Sound', 'Sound'), ('Motion', 'Motion'), ('Proximity', 'Proximity'), ('Gas', 'Gas'), ('Color', 'Color'), ('Electricity', 'Electricity'), ('Magnetic', 'Magnetic'), ('Acceleration', 'Acceleration'), ('Gyroscope', 'Gyroscope'), ('Barometer', 'Barometer'), ('Infrared', 'Infrared'), ('UV', 'UV'), ('GPS', 'GPS'), ('Flow', 'Flow'), ('pH', 'pH'), ('Humectant', 'Humectant'), ('Smoke', 'Smoke'), ('CO2', 'CO2'), ('CO', 'CO'), ('Ozone', 'Ozone'), ('Water', 'Water'), ('Vibration', 'Vibration'), ('Weight', 'Weight'), ('Level', 'Level'), ('Radiation', 'Radiation'), ('Other', 'Other')], default='Other', max_length=150)),
                ('Active', models.BooleanField(default=False)),
                ('Description', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Visualization_id', models.CharField(max_length=50, null=True)),
                ('Doc_field', models.CharField(max_length=50, null=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.device')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='Organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='UseCase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.usecases'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Alert_id', models.CharField(max_length=250, null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Watcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.watcher')),
            ],
        ),
    ]
