# Generated by Django 4.2.2 on 2023-07-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='param',
            name='Type',
        ),
        migrations.AddField(
            model_name='param',
            name='DataType',
            field=models.CharField(choices=[('Integer', 'Integer'), ('Boolean', 'Boolean'), ('Double', 'Double'), ('String', 'String')], default='Integer', max_length=50),
        ),
    ]
