# Generated by Django 4.1.4 on 2023-08-03 17:51

import Backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_role_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='Service',
            field=models.CharField(choices=[('Predictive Maintenance', 'Predictive Maintenance'), ('Inventory Management', 'Inventory Management')], default='Predictive Maintenance', max_length=50),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Action', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=50)),
                ('Body', models.CharField(max_length=1000, null=True)),
                ('User_list', models.CharField(max_length=1000, null=True)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Watcher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.watcher')),
            ],
        ),
    ]
