# Generated by Django 4.2.2 on 2023-08-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_organization_service_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='breached_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='breached_param',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='breached_threshold',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
