# Generated by Django 4.2.2 on 2023-08-25 03:25

import Backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.job'),
        ),
        migrations.AddField(
            model_name='action',
            name='Type',
            field=models.CharField(choices=[('Watcher', 'Watcher'), ('Anomaly', 'Anomaly')], default='Watcher', max_length=50),
        ),
        migrations.CreateModel(
            name='AnomalyAlert',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Severity', models.CharField(max_length=50, null=True)),
                ('Detector', models.CharField(max_length=50, null=True)),
                ('Time', models.CharField(max_length=50, null=True)),
                ('Typical', models.CharField(max_length=50, null=True)),
                ('Actual', models.CharField(max_length=50, null=True)),
                ('Description', models.CharField(max_length=50, null=True)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.job')),
            ],
        ),
    ]
