# Generated by Django 4.2.2 on 2023-08-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_action_job_action_type_anomalyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyalert',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
