# Generated by Django 4.2.2 on 2023-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_anomalyalert_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='Role_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
