# Generated by Django 4.2.2 on 2023-08-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_role_role_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='Chart_type',
            field=models.CharField(choices=[('area', 'area'), ('line', 'line'), ('pie', 'pie'), ('metric', 'metric'), ('bar_stacked', 'bar_stacked')], default='area', max_length=50),
        ),
    ]
