# Generated by Django 4.2.2 on 2023-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Unresolved', 'Unresolved'), ('Resolved', 'Resolved'), ('Acknowledged', 'Acknowledged')], default='Unresolved', max_length=50, null=True),
        ),
    ]
