# Generated by Django 4.2.2 on 2023-09-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Canceled', 'Canceled'), ('Acknowledged', 'Acknowledged')], default='Unresolved', max_length=50, null=True),
        ),
    ]
