# Generated by Django 4.2.2 on 2023-09-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Canceled', 'Canceled'), ('Acknowledged', 'Acknowledged'), ('New', 'New')], default='New', max_length=50, null=True),
        ),
    ]
