# Generated by Django 4.2.2 on 2023-09-15 12:34

import Backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0014_alter_alert_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirflowJob',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Status', models.CharField(choices=[('In Progess....', 'In Progress....'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='In Progress....', max_length=50)),
                ('Type', models.CharField(choices=[('Training', 'Training'), ('Prediction', 'Prediction')], default='Prediction', max_length=50)),
                ('Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.device')),
            ],
        ),
    ]
