# Generated by Django 4.2.2 on 2023-09-20 15:02

import Backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0017_alter_airflowjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('N_input', models.IntegerField(default=1)),
                ('Training_size', models.IntegerField(default=1)),
                ('File_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='airflowjob',
            name='File_name',
        ),
        migrations.AddField(
            model_name='airflowjob',
            name='Dag_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='airflowjob',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('ID', models.SlugField(default=Backend.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Prediction_size', models.IntegerField(default=1)),
                ('File_name', models.CharField(max_length=100, null=True)),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.airflowjob')),
                ('Model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.mlmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='Job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.airflowjob'),
        ),
    ]
