# Generated by Django 4.2.2 on 2023-10-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0019_mlmodel_created_date_prediction_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='Column_order',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
