# Generated by Django 4.2.2 on 2023-10-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0020_mlmodel_column_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='Misc_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='Type',
            field=models.CharField(choices=[('Watcher', 'Watcher'), ('Anomaly', 'Anomaly'), ('Geofence', 'Geofence')], default='Watcher', max_length=50),
        ),
    ]
