# Generated by Django 4.2.2 on 2023-10-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0021_action_misc_id_alter_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='CertificateARN',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
