# Generated by Django 4.2.2 on 2023-11-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0023_alter_action_type_patterndetector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Job_Description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Organization',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='Phone_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
