# Generated by Django 4.2.2 on 2023-11-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0025_verificationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=100, null=True)),
                ('last_generated', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.role')),
            ],
        ),
    ]
