# Generated by Django 4.2.2 on 2023-12-15 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Backend', '0026_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='watcher',
            name='Conditions',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watcher',
            name='Params',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='watcher',
            name='Thresholds',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='uploads/')),
                ('File_name', models.CharField(max_length=255, null=True)),
                ('File_size', models.BigIntegerField(null=True)),
                ('File_format', models.CharField(max_length=50, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
