# Generated by Django 4.2.2 on 2023-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0029_extrakey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='Column_order',
            field=models.CharField(max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='File_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
