# Generated by Django 4.2.2 on 2023-12-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0030_alter_mlmodel_column_order_alter_mlmodel_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='Column_order',
            field=models.TextField(null=True),
        ),
    ]
