# Generated by Django 4.2.2 on 2023-12-22 07:10

import DigitalTwin.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Backend', '0032_profile_push_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twin',
            fields=[
                ('ID', models.SlugField(default=DigitalTwin.models.custom_id, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150, null=True)),
                ('Active', models.BooleanField(default=False, null=True)),
                ('Completed', models.BooleanField(default=False, null=True)),
                ('Description', models.TextField(null=True)),
                ('Type', models.CharField(choices=[('Asset', 'Asset'), ('Component', 'Component'), ('Simulation', 'Simulation')], max_length=50)),
                ('Created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('Files', models.TextField(null=True)),
                ('Device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.device')),
            ],
        ),
    ]
